### ISSUE TITLE
Issues with Raspberry Pi A+

### ISSUE THREAD

**Issue by thymjan** [dalexgray/RaspberryPI_HTU21DF#2]
Hi,
now I've tested your python-version for HTU21DF too. But I had no luck. Also received errors:

```
~/RaspberryPI_HTU21DF $ sudo python HTU21DF_test.py 
sending reset...
Traceback (most recent call last):
  File "HTU21DF_test.py", line 9, in <module>
    temperature = HTU21DF.read_temperature()
  File "/home/pi/RaspberryPI_HTU21DF/HTU21DF.py", line 54, in read_temperature
    pi.i2c_write_byte(handle, rdtemp) # send read temp command
  File "/usr/local/lib/python2.7/dist-packages/pigpio.py", line 2195, in i2c_write_byte
    _pigpio_command(self.sl, _PI_CMD_I2CWS, handle, byte_val))
  File "/usr/local/lib/python2.7/dist-packages/pigpio.py", line 796, in _u2i
    raise error(error_text(v))
pigpio.error: 'I2C write failed'
```

It seems to be the same problem (like the C-written version), when trying to write on the I2C-bus.

I've updated my firmware to `Linux 4.1.4+ #808 PREEMPT Thu Aug 6 15:51:03 BST 2015 armv6l GNU/Linux`. Maybe that's the problem?

If I change - as you suggested - from `bus = 1`to `bus = 0` the output looks like this:

```
sending reset...
Traceback (most recent call last):
  File "HTU21DF_test.py", line 9, in <module>
    temperature = HTU21DF.read_temperature()
  File "/home/pi/RaspberryPI_HTU21DF/HTU21DF.py", line 53, in read_temperature
    handle = pi.i2c_open(bus, addr) # open i2c bus
  File "/usr/local/lib/python2.7/dist-packages/pigpio.py", line 2150, in i2c_open
    self.sl, _PI_CMD_I2CO, i2c_bus, i2c_address, 4, extents))
  File "/usr/local/lib/python2.7/dist-packages/pigpio.py", line 796, in _u2i
    raise error(error_text(v))
pigpio.error: "can't open I2C device"
```

So I think the A+ version uses `bus = 1` either, does it?

I don't know why, but it seems that there is a problem with the rights for accessing the I2C bus on my installation. 

Stefan

**Comment by thymjan** [comment]
Ohhh. I'm stupid. Attached the ground to the wrong pin. Now it works. Sorry about that.
Thanks for your help.
